AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - lib/epithet.rb

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/PerceivedComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Naming/ConstantName:
  Exclude:
    - lib/epithet.rb

Naming/MethodParameterName:
  MinNameLength: 1

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CaseEquality:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/EmptyClassDefinition:
  AllowedParentClasses:
    - ArgumentError

Style/FormatString:
  EnforcedStyle: percent

Style/NumberedParametersLimit:
  Max: 2

Style/NumericPredicate:
  Enabled: false

Style/Semicolon:
  Exclude:
    - lib/epithet.rb

Style/RedundantFetchBlock:
  Exclude:
    - examples/**/*.rb

Style/CharacterLiteral:
  Exclude:
    - test/**/*.rb

Style/StringConcatenation:
  Exclude:
    - test/**/*.rb

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - test/**/*.rb

Style/TrailingCommaInHashLiteral:
  Exclude:
    - test/**/*.rb
