[tools]
ruby = "4.0"

[tasks.test]
run = "bundle exec rake test"

[tasks.matrix]
run = [
  "mise exec ruby@3.4 -- bundle install",
  "mise exec ruby@3.4 -- bundle exec rake test",
  "mise exec ruby@4.0 -- bundle install",
  "mise exec ruby@4.0 -- bundle exec rake test",
  "bundle exec rubocop"
]

[tasks.cop]
run = "bundle exec rubocop"

[tasks.doc]
run = "bundle exec rake rdoc && open doc/index.html"
